# -*- coding: utf-8 -*-
"""GlobalAlHubProje.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EPwt1XoERPGtutQ6s3ZaFFSBsaO-pAUU
"""

from datetime import datetime

class Library:
    def __init__(self):
        self.books = []

    def list_books(self):
        if not self.books:
            print("Kütüphane Kitap Bulunmamaktadır.")
        else:
            print("Kitaplar")
            for title, book_info in self.books:
              print(f" -{title}{book_info}")


    def add_book(self, title, author, year, date):
        book_info = f"Kitap Başlığı: {title}\nYazar: {author}\nSayfa Sayısı: {year}\nTarih: {date}"
        self.books.append((title,book_info))
        print(f"\nKitap Bilgileri:\n{book_info}\nKütüphaneye '{title}' '{author}' Eklendi:")

    def remove_book_by_title(self, title):
        removed_books = [book for book in self.books if title.lower() in book[0].lower()]

        if not removed_books:
            print(f"Kitap adında '{title}' içeren kitap kütüphanede bulunamadı.")
        else:
            for removed_book in removed_books:
                self.books.remove(removed_book)
                print(f"Kitap '{removed_book[0]}' kütüphaneden silindi")

    def write_file(self,book_info):
      with open("books.txt","a+",encoding="utf-8")as file:
        file.write(f"{book_info}\n")
        print(f"Kitap bilgileri books.txt dosyasına eklenmiştir.")

lib = Library()

def menu():
    while True:
        print("\n*** MENU ***")
        print("1) Kitapları Listele")
        print("2) Kitap Ekle")
        print("3) Kitap Sil")
        print("q) Çıkış")

        choice = input("Menüden Numara Seçin: ")

        if choice == '1':
            lib.list_books()
        elif choice == '2':
            title = input("Kitap Başlığını Ekleyin: ")
            author = input("Yazar Adını Ekleyin: ")
            year = input("Sayfa Sayısı Ekleyin: ")
            date_str = input("Tarihi Ekleyin (GG.AA.YYYY): ")

            try:
                date = datetime.strptime(date_str, "%d.%m.%Y").date()
            except ValueError:
                print("Hatalı tarih formatı, lütfen GG.AA.YYYY formatında girin.")
                continue

            lib.add_book(title, author, year, date)
        elif choice == '3':
            title_to_remove = input("Silmek istediğiniz kitabın adını girin: ")
            lib.remove_book_by_title(title_to_remove)
        elif choice == "q":
            print("Çıkış")
            break
        else:
            print("1-q arası bir değer seçin")


menu()